kind = "DojoModel"
class_hash = "0x2ee9ebe75fc086dd63c029fb7eb582f16b2b231f1cdb0f8cc3803c4ec8281f9"
original_class_hash = "0x2ee9ebe75fc086dd63c029fb7eb582f16b2b231f1cdb0f8cc3803c4ec8281f9"
abi = "manifests/slotdev/base/abis/models/zkube-Settings-161104df.json"
tag = "zkube-Settings"
qualified_path = "zkube::models::index::settings"
manifest_name = "zkube-Settings-161104df"

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "free_daily_credits"
type = "u8"
key = false

[[members]]
name = "daily_mode_price"
type = "felt252"
key = false

[[members]]
name = "normal_mode_price"
type = "felt252"
key = false
