[world]
kind = "WorldContract"
class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
original_class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
abi = "manifests/slotdev/deployment/abis/dojo-world.json"
address = "0x19fe9c3f2e740b08df807afae6a7e882685c801d3a552f5728e65fc2bac58b4"
transaction_hash = "0x4fec2c450f0a6670249acdc79673086bc70433b4d578fdfa167420a7d12a2d3"
block_number = 3
seed = "zKube"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "slotdev"
rpc_url = "https://api.cartridge.gg/x/zkube-slotdev/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x2b4f0e952d12b43d3bb93639be357a7ece3aa364f55d8f1f1e6e6ca68c7f285"
class_hash = "0x32ff262fda01b4c3bb3f0509fc23b75a13ce0daf6e45539d37e33c928ad90b3"
original_class_hash = "0x32ff262fda01b4c3bb3f0509fc23b75a13ce0daf6e45539d37e33c928ad90b3"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/contracts/zkube-account-6d28004d.json"
reads = []
writes = [
    "zkube-Player",
    "zkube-Game",
    "zkube-Tournament",
]
init_calldata = []
tag = "zkube-account"
manifest_name = "zkube-account-6d28004d"

[[contracts]]
kind = "DojoContract"
address = "0x5bad75c9017268d7072f4b4946aa7bcd8126bef87e1561ab75df807f9889aad"
class_hash = "0x1613479aa485d0e3e0630f5024b05697009a91f4ce051f9d188ef70c5e0c2fd"
original_class_hash = "0x1613479aa485d0e3e0630f5024b05697009a91f4ce051f9d188ef70c5e0c2fd"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/contracts/zkube-dailygame-2e941267.json"
reads = []
writes = [
    "zkube-Player",
    "zkube-Game",
    "zkube-Tournament",
]
init_calldata = ["0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"]
tag = "zkube-dailygame"
manifest_name = "zkube-dailygame-2e941267"

[[models]]
kind = "DojoModel"
class_hash = "0x58feddde1281dd90eaa745e765c66dc32b3b13f741b263c64c5ec31835bfb48"
original_class_hash = "0x58feddde1281dd90eaa745e765c66dc32b3b13f741b263c64c5ec31835bfb48"
abi = "manifests/slotdev/deployment/abis/models/zkube-Game-17e542e0.json"
tag = "zkube-Game"
manifest_name = "zkube-Game-17e542e0"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "over"
type = "bool"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false

[[models.members]]
name = "moves"
type = "u32"
key = false

[[models.members]]
name = "next_row"
type = "u32"
key = false

[[models.members]]
name = "next_color"
type = "u32"
key = false

[[models.members]]
name = "hammer_bonus"
type = "u8"
key = false

[[models.members]]
name = "wave_bonus"
type = "u8"
key = false

[[models.members]]
name = "totem_bonus"
type = "u8"
key = false

[[models.members]]
name = "combo_counter"
type = "u8"
key = false

[[models.members]]
name = "blocks"
type = "felt252"
key = false

[[models.members]]
name = "colors"
type = "felt252"
key = false

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models.members]]
name = "mode"
type = "u8"
key = false

[[models.members]]
name = "start_time"
type = "u64"
key = false

[[models.members]]
name = "tournament_id"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5f4a8383dfc575b1dbd826cf4bce31b22f1c4395749e2b6ad9c905e3324e5c2"
original_class_hash = "0x5f4a8383dfc575b1dbd826cf4bce31b22f1c4395749e2b6ad9c905e3324e5c2"
abi = "manifests/slotdev/deployment/abis/models/zkube-Player-a3c56d30.json"
tag = "zkube-Player"
manifest_name = "zkube-Player-a3c56d30"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "game_id"
type = "u32"
key = false

[[models.members]]
name = "hammer_bonus"
type = "u8"
key = false

[[models.members]]
name = "wave_bonus"
type = "u8"
key = false

[[models.members]]
name = "totem_bonus"
type = "u8"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "points"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x40192a8af7bea738cee0feffb7de37f6b15e21f6809cff453268e65f240d1b6"
original_class_hash = "0x40192a8af7bea738cee0feffb7de37f6b15e21f6809cff453268e65f240d1b6"
abi = "manifests/slotdev/deployment/abis/models/zkube-Tournament-120c37d1.json"
tag = "zkube-Tournament"
manifest_name = "zkube-Tournament-120c37d1"

[[models.members]]
name = "id"
type = "u64"
key = true

[[models.members]]
name = "prize"
type = "felt252"
key = false

[[models.members]]
name = "top1_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top2_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top3_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top1_score"
type = "u32"
key = false

[[models.members]]
name = "top2_score"
type = "u32"
key = false

[[models.members]]
name = "top3_score"
type = "u32"
key = false

[[models.members]]
name = "top1_claimed"
type = "bool"
key = false

[[models.members]]
name = "top2_claimed"
type = "bool"
key = false

[[models.members]]
name = "top3_claimed"
type = "bool"
key = false
