kind = "DojoContract"
class_hash = "0x2f7914bdbd84ce81ca69f2fdf3fa8679a9614a2fa3867ed23fa1e9f4919ba53"
original_class_hash = "0x2f7914bdbd84ce81ca69f2fdf3fa8679a9614a2fa3867ed23fa1e9f4919ba53"
base_class_hash = "0x0"
abi = "manifests/slottest/abis/base/contracts/zkube_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkube::systems::actions::actions"
