kind = "DojoContract"
class_hash = "0x7c617ebc7f0bde51e5c9a1ca6c5014e8c88c9c49c5b5dd2c4b32422b79252b9"
original_class_hash = "0x7c617ebc7f0bde51e5c9a1ca6c5014e8c88c9c49c5b5dd2c4b32422b79252b9"
base_class_hash = "0x0"
abi = "manifests/slotdev/base/abis/contracts/zkube-settings-3b7c4918.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-settings"
systems = [
    "update_zkorp_address",
    "update_free_daily_credits",
    "update_daily_mode_price",
    "update_normal_mode_price",
    "set_admin",
    "delete_admin",
]
manifest_name = "zkube-settings-3b7c4918"
