kind = "DojoContract"
class_hash = "0x1311fd08bba7968e02c94a41d90d1c0a5bbce07de636b6fd33ac6770e4e6f70"
original_class_hash = "0x1311fd08bba7968e02c94a41d90d1c0a5bbce07de636b6fd33ac6770e4e6f70"
base_class_hash = "0x0"
abi = "manifests/slotdev/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "claim",
    "sponsor",
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
