kind = "DojoContract"
class_hash = "0x1de897d44026065022fb6f719f28f5d07bfd8e30d6f1d0749fd8073ef25be7f"
original_class_hash = "0x1de897d44026065022fb6f719f28f5d07bfd8e30d6f1d0749fd8073ef25be7f"
base_class_hash = "0x0"
abi = "manifests/slotdev/base/abis/contracts/zkube-dailygame-2e941267.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-dailygame"
manifest_name = "zkube-dailygame-2e941267"
