kind = "DojoContract"
class_hash = "0x2b9ccdb8c674605563250fc8c161a3501cd996e414f5af69481b988b5be5973"
original_class_hash = "0x2b9ccdb8c674605563250fc8c161a3501cd996e414f5af69481b988b5be5973"
base_class_hash = "0x0"
abi = "manifests/slotdev/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
