kind = "DojoModel"
class_hash = "0x77b1d431010a90b1e96e1f25f3a8b0b5031d53c2727c6bbdf69352a1b9fe7bf"
original_class_hash = "0x77b1d431010a90b1e96e1f25f3a8b0b5031d53c2727c6bbdf69352a1b9fe7bf"
abi = "manifests/dev/abis/base/models/zkube_models_index_game.json"
name = "zkube::models::index::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "bonuses"
type = "u16"
key = false

[[members]]
name = "blocks"
type = "felt252"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false
