kind = "DojoModel"
class_hash = "0x5f4a8383dfc575b1dbd826cf4bce31b22f1c4395749e2b6ad9c905e3324e5c2"
original_class_hash = "0x5f4a8383dfc575b1dbd826cf4bce31b22f1c4395749e2b6ad9c905e3324e5c2"
abi = "manifests/dev/base/abis/models/zkube-Player-a3c56d30.json"
tag = "zkube-Player"
manifest_name = "zkube-Player-a3c56d30"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "game_id"
type = "u32"
key = false

[[members]]
name = "hammer_bonus"
type = "u8"
key = false

[[members]]
name = "wave_bonus"
type = "u8"
key = false

[[members]]
name = "totem_bonus"
type = "u8"
key = false

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "points"
type = "u32"
key = false
