kind = "DojoModel"
class_hash = "0x6af0db3fffcd6a03fde475e8706a713a51a6ea8feda79b0a8c7aa07b93c4d6f"
original_class_hash = "0x6af0db3fffcd6a03fde475e8706a713a51a6ea8feda79b0a8c7aa07b93c4d6f"
abi = "manifests/dev/base/abis/models/zkube-Credits-20403c75.json"
tag = "zkube-Credits"
qualified_path = "zkube::models::index::credits"
manifest_name = "zkube-Credits-20403c75"

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "id"
type = "u64"
key = false

[[members]]
name = "remaining"
type = "u8"
key = false
