kind = "DojoModel"
class_hash = "0x518d5600abe39045eca19b504a360619479532921f49ffc218f6856b1b1eab2"
original_class_hash = "0x518d5600abe39045eca19b504a360619479532921f49ffc218f6856b1b1eab2"
abi = "manifests/dev/base/abis/models/zkube-Settings-161104df.json"
tag = "zkube-Settings"
qualified_path = "zkube::models::index::settings"
manifest_name = "zkube-Settings-161104df"

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "is_set"
type = "bool"
key = false

[[members]]
name = "free_daily_credits"
type = "u8"
key = false

[[members]]
name = "daily_mode_price"
type = "felt252"
key = false

[[members]]
name = "normal_mode_price"
type = "felt252"
key = false
