kind = "DojoModel"
class_hash = "0x4bf2e070c7936a710afbc9a6e93288d9aa7d524ae7c3bb39e2d1a5ab0f08ad2"
original_class_hash = "0x4bf2e070c7936a710afbc9a6e93288d9aa7d524ae7c3bb39e2d1a5ab0f08ad2"
abi = "manifests/slottest/abis/base/models/zkube_models_index_game.json"
name = "zkube::models::index::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "difficulty"
type = "u8"
key = false

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "next_row"
type = "u32"
key = false

[[members]]
name = "next_color"
type = "u32"
key = false

[[members]]
name = "hammer_bonus"
type = "u8"
key = false

[[members]]
name = "wave_bonus"
type = "u8"
key = false

[[members]]
name = "totem_bonus"
type = "u8"
key = false

[[members]]
name = "combo_counter"
type = "u8"
key = false

[[members]]
name = "blocks"
type = "felt252"
key = false

[[members]]
name = "colors"
type = "felt252"
key = false

[[members]]
name = "player_id"
type = "felt252"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false
