kind = "DojoContract"
class_hash = "0x50a71605b38e966a2049a7f63851a50b3f9296a7c56f7f4ee339e7ab784d475"
original_class_hash = "0x50a71605b38e966a2049a7f63851a50b3f9296a7c56f7f4ee339e7ab784d475"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
