kind = "DojoContract"
class_hash = "0x633c4760b73be82e6a42bcce1e5017477f83bd8f7a459594c03a73c02983700"
original_class_hash = "0x633c4760b73be82e6a42bcce1e5017477f83bd8f7a459594c03a73c02983700"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
