kind = "DojoContract"
class_hash = "0x1a7c904419829a724e8d80eaed61a90eea559e1ec0c532fc15f0ed31ae6d268"
original_class_hash = "0x1a7c904419829a724e8d80eaed61a90eea559e1ec0c532fc15f0ed31ae6d268"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/zkube-tournament-2101600e.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-tournament"
systems = [
    "claim",
    "sponsor",
]
manifest_name = "zkube-tournament-2101600e"
