kind = "DojoContract"
class_hash = "0x9b89b1f20504124fde2b48853ddd233db87e26f5a4cd380fcc78299bbb736c"
original_class_hash = "0x9b89b1f20504124fde2b48853ddd233db87e26f5a4cd380fcc78299bbb736c"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/zkube-settings-3b7c4918.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-settings"
systems = [
    "update_zkorp_address",
    "update_free_daily_credits",
    "update_daily_mode_price",
    "update_normal_mode_price",
    "set_admin",
    "delete_admin",
]
manifest_name = "zkube-settings-3b7c4918"
