kind = "DojoContract"
class_hash = "0x1e5225cd9492cf089f9bcb113a4b5123525b08f9ac69f583a59048d364050d7"
original_class_hash = "0x1e5225cd9492cf089f9bcb113a4b5123525b08f9ac69f583a59048d364050d7"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkube_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkube::systems::actions::actions"
