kind = "DojoContract"
class_hash = "0x4e2ad53cb0c7a05884e65ced79c0ba292c731a2189f6b6f2e2648c52e4fa531"
original_class_hash = "0x4e2ad53cb0c7a05884e65ced79c0ba292c731a2189f6b6f2e2648c52e4fa531"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
manifest_name = "zkube-play-19ee70b3"
