kind = "DojoContract"
class_hash = "0x13b2fca532997e789de9e51aad67d530ea6300976b03617831443e95fff40c0"
original_class_hash = "0x13b2fca532997e789de9e51aad67d530ea6300976b03617831443e95fff40c0"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-account-6d28004d.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-account"
systems = [
    "create",
    "rename",
]
manifest_name = "zkube-account-6d28004d"
