kind = "DojoContract"
class_hash = "0x22d10b435abac188d128da25914f06ec8b11353a7bd3e8be178a634c9633481"
original_class_hash = "0x22d10b435abac188d128da25914f06ec8b11353a7bd3e8be178a634c9633481"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkube_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkube::systems::actions::actions"
