kind = "DojoContract"
class_hash = "0x7f52c0b17b60e0a8d333a1746bc6d089f02f9e4dce14eb665be0d0d9d235df2"
original_class_hash = "0x7f52c0b17b60e0a8d333a1746bc6d089f02f9e4dce14eb665be0d0d9d235df2"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkube_systems_dailygame_dailygame.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkube::systems::dailygame::dailygame"
