kind = "DojoContract"
class_hash = "0x57ee42774aca2fd3fb1a80aa914cd53b4e249e210ae93ca536f200f3d81038b"
original_class_hash = "0x57ee42774aca2fd3fb1a80aa914cd53b4e249e210ae93ca536f200f3d81038b"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkube_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkube::systems::actions::actions"
