kind = "DojoContract"
class_hash = "0x31e3334898079806c1848473b06cf61ccc64ce2176dd9768fccc4ba233c2652"
original_class_hash = "0x31e3334898079806c1848473b06cf61ccc64ce2176dd9768fccc4ba233c2652"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-account-6d28004d.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-account"
systems = [
    "create",
    "rename",
]
manifest_name = "zkube-account-6d28004d"
