kind = "DojoContract"
class_hash = "0x3cba80818edd75a736cde803304fece4d16f04f771d8a09905ef64a5f524280"
original_class_hash = "0x3cba80818edd75a736cde803304fece4d16f04f771d8a09905ef64a5f524280"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "claim",
    "sponsor",
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
