kind = "DojoContract"
class_hash = "0x26e37b0086bd2c75f4080e6f2f6f19f80b53fa23d39380fbc2ef7c50fd80bbd"
original_class_hash = "0x26e37b0086bd2c75f4080e6f2f6f19f80b53fa23d39380fbc2ef7c50fd80bbd"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "claim",
    "sponsor",
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
