kind = "DojoContract"
class_hash = "0x4f04b1804c8d2e0f298ab10d8b9a7ee64aade852cd9a8407840597d3bb383ae"
original_class_hash = "0x4f04b1804c8d2e0f298ab10d8b9a7ee64aade852cd9a8407840597d3bb383ae"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkube_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkube::systems::actions::actions"
