kind = "DojoContract"
class_hash = "0xe4a67a7fb710228b95d4563c84a7adbe420329a0bc7752570ca2ece1e411e7"
original_class_hash = "0xe4a67a7fb710228b95d4563c84a7adbe420329a0bc7752570ca2ece1e411e7"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "claim",
    "sponsor",
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
