kind = "DojoContract"
class_hash = "0x49ed66c973ca06a5e60d1915bbfbd076a8f07325eced4124dd3f54ced79ff9"
original_class_hash = "0x49ed66c973ca06a5e60d1915bbfbd076a8f07325eced4124dd3f54ced79ff9"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-settings-3b7c4918.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-settings"
systems = [
    "update_free_daily_credits",
    "update_daily_mode_price",
    "update_normal_mode_price",
    "set_admin",
    "delete_admin",
]
manifest_name = "zkube-settings-3b7c4918"
