kind = "DojoContract"
class_hash = "0x270fe124fe9c4abfdcdb165e6e4cd75fcfd781cd76cf6f01f20454b8b841d89"
original_class_hash = "0x270fe124fe9c4abfdcdb165e6e4cd75fcfd781cd76cf6f01f20454b8b841d89"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-zkorp-6cdc1046.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-zkorp"
systems = [
    "claim",
    "sponsor",
]
manifest_name = "zkube-zkorp-6cdc1046"
