kind = "DojoContract"
class_hash = "0x4e761b8f91319d948361bf3b160bffd8a7add466c8b0244f75f9275532805a7"
original_class_hash = "0x4e761b8f91319d948361bf3b160bffd8a7add466c8b0244f75f9275532805a7"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/zkube_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkube::systems::actions::actions"
