kind = "DojoContract"
class_hash = "0x47c09430172cb61d5c433f29f3cc0937f08fe03a650738f1aabe6257865f5e3"
original_class_hash = "0x47c09430172cb61d5c433f29f3cc0937f08fe03a650738f1aabe6257865f5e3"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-settings-3b7c4918.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-settings"
systems = [
    "update_free_daily_credits",
    "update_daily_mode_price",
    "update_normal_mode_price",
    "set_admin",
    "delete_admin",
]
manifest_name = "zkube-settings-3b7c4918"
